### PR TITLE
Major rewrite: Use Gtk.IconTheme to find icons (fixes #22)

### LINKED ISSUE #22: Cant change color of folders when using mint-y-dark
When using Mint-y-Dark icon, the colors are unavailable

### PR DESCRIPTION
**Pull request by okaestne**
Use existing functions in Gtk instead of:
* walking directories
* parsing index.theme files
* other hacky string concat stuff..

Fixes:
* #22 (Mint-Y-Dark icons)
* folders on desktop can't be colored

### CODE REVIEW

**Comment by okaestne** [comment]
Open points:
* Can caja use python3 so that I can apply these changes to the caja version as well? What do you think about a common, shared base script?
* can you please check the debian packaging stuff (compat level 7 is deprecated)? Don't have any experience...
* I stumbled upon some bugs regarding the selection of elements (trying to recolor the same set of folders results in a random sub-set of the selection). I will create a issue in the nemo repo for that soon.

**Comment by mtwebster** [comment]
It looks as though they've ported it to use python3 as well, so it's probably fine to share/subclass if you want, though I think there are substantial differences between the caja- and nemo-extension api.

**Comment by okaestne** [comment]
@mtwebster What about backward compat with Mint Mate <20.X that has no Caja with py3? second branch? no further updates?

**Comment by mtwebster** [comment]
Don't worry about backward compatibility (we don't generally worry about that when moving to a new major version, as it can be very difficult to accomodate both package bases that are 2+ years apart.

The only things we do that for are Mint-specific programs.

**Comment by okaestne** [comment]
@mtwebster Alright. I would prefer opening another pull request for that py3 migration, if you don't mind. Is there anything else to be done before merging this PR?

**Comment by mtwebster** [comment]
Just squash maybe.  It's ok to have a few commits, just not 11.  I can squash as I merge if you want also.

 Works well - what is the dark icon set problem? (issue #22)

**Comment by okaestne** [comment]
@mtwebster ofc you may unite the commits, if you need it for some reason. ;)

Regarding #22 : the extension didn't work at all when using the Mint-Y-Dark theme and just threw exceptions.

If you need to write a changelog for all commits:

* fixes #22 (Mint-Y-Dark)
* fix: now works on desktop
* fix: respect scale factor (Hi-DPI)
* improvement: Use Gtk3 functions for more reliable icon lookup and reduced code size
* improvement: remove subprocess call, better performance when coloring many folders

**Pull request merged**
